project_id = "yczbkoirwbugulqdlsag"

[functions.categorize-expense]
verify_jwt = false

[functions.suggest-budget]
verify_jwt = false

[functions.suggest-shopping-items]
verify_jwt = false

[functions.auto-allocate-savings]
verify_jwt = false

[functions.process-recurring-transactions]
verify_jwt = false